networks:
  proxynet:
    driver: bridge

services:
  testtask.minesweeper.service:
    image: ${DOCKER_REGISTRY-}testtaskminesweeperservice
    build:
      context: .
      dockerfile: TestTask.Minesweeper.Service/Dockerfile
    depends_on:
      database:
        condition: service_healthy
      logs.storage:
        condition: service_started
    networks:
       - proxynet
  database:
    image: postgres:latest
    healthcheck:
       test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
       interval: 10s
       retries: 5
       start_period: 30s
       timeout: 10s
    restart: always
    ports:
       - "5434:5432"
    networks:
       - proxynet
  logs.storage:
     image: mongo
     restart: always
     ports:
       - "27017:27017"
     networks:
       - proxynet
