networks:
  proxynet:
    driver: bridge

services:
  testtask.minesweeper.service:
    image: ${DOCKER_REGISTRY-}testtaskminesweeperservice
    build:
      context: .
      dockerfile: TestTask.Minesweeper.Service/Dockerfile
    depends_on:
      database:
        condition: service_started
      logs.storage:
        condition: service_started
    networks:
       - proxynet
  database:
    image: postgres:latest
    restart: always
    ports:
       - "5434:5432"
    networks:
       - proxynet
  logs.storage:
     image: mongo
     restart: always
     ports:
       - "27017:27017"
     networks:
       - proxynet
